"""Small SQLite/Postgres bridge for this app's fixed, parameterized SQL."""
from contextlib import contextmanager
import re
import sqlite3

try:
    import psycopg
except ImportError:
    psycopg = None

DatabaseError = (sqlite3.DatabaseError,) + ((psycopg.Error,) if psycopg else ())


class Row(dict):
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def rows(cursor):
    names = [column.name for column in cursor.description or ()]
    return lambda values: Row(zip(names, values))


class Postgres:
    def __init__(self, location):
        if psycopg is None:
            raise RuntimeError("Install requirements.txt to use PostgreSQL.")
        self.connection = psycopg.connect(location, autocommit=True, row_factory=rows, connect_timeout=10, prepare_threshold=None)

    def execute(self, sql, parameters=()):
        sql = sql.strip().rstrip(";")
        if sql.upper() == "BEGIN IMMEDIATE":
            self.connection.execute("BEGIN")
            self.connection.execute("SET LOCAL statement_timeout = '15s'")
            self.connection.execute("SET LOCAL lock_timeout = '10s'")
            # ponytail: one database-wide writer lock; split by calendar if multiple calendars are added.
            return self.connection.execute("SELECT pg_advisory_xact_lock(8247139)")
        if sql.upper().startswith("PRAGMA TABLE_INFO"):
            table = re.fullmatch(r"PRAGMA table_info\(([a-z_]+)\)", sql, re.I)
            if not table:
                raise ValueError("Unsupported table metadata query")
            return self.connection.execute("""SELECT ordinal_position-1 AS cid, column_name AS name,
                data_type AS type, is_nullable AS nullable, column_default AS dflt_value
                FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=%s
                ORDER BY ordinal_position""", (table[1],))
        if sql.upper().startswith("PRAGMA "):
            return self.connection.execute("SELECT 1 WHERE FALSE")
        if sql.upper().startswith(("CREATE TABLE ", "ALTER TABLE ")):
            sql = re.sub(r"\bINTEGER\b", "BIGINT", sql, flags=re.I)
            sql = re.sub(r"BIGINT PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql, flags=re.I)
        insert = re.match(r"INSERT INTO (bookings|requests|booking_history)\b", sql, re.I)
        if insert and "RETURNING" not in sql.upper():
            sql += " RETURNING id"
        # Only static app SQL enters here; user values always remain bound parameters.
        cursor = self.connection.execute(sql.replace("%", "%%").replace("?", "%s"), parameters)
        if insert:
            return InsertResult(cursor)
        return cursor

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


class InsertResult:
    def __init__(self, cursor):
        row = cursor.fetchone()
        self.lastrowid = row["id"] if row else None
        self.rowcount = cursor.rowcount


def connect(location):
    if str(location).startswith(("postgres://", "postgresql://")):
        return Postgres(location)
    connection = sqlite3.connect(location, timeout=15)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys=ON")
    return connection


@contextmanager
def transaction(connection):
    connection.execute("BEGIN IMMEDIATE")
    try:
        yield connection
        connection.commit()
    except BaseException:
        connection.rollback()
        raise


def initialize(connection, schema):
    """Explicit migration; production entrypoints only validate an already migrated schema."""
    connection.execute("PRAGMA journal_mode=WAL")
    with transaction(connection):
        for statement in schema.split(";"):
            if statement.strip():
                connection.execute(statement)
        columns = {row["name"] for row in connection.execute("PRAGMA table_info(bookings)").fetchall()}
        if "sequence" not in columns:
            connection.execute("ALTER TABLE bookings ADD COLUMN sequence INTEGER NOT NULL DEFAULT 0")
            connection.execute("UPDATE bookings SET sequence=1 WHERE cancelled IS NOT NULL")
        if "updated" not in columns:
            connection.execute("ALTER TABLE bookings ADD COLUMN updated INTEGER")
            connection.execute("UPDATE bookings SET updated=COALESCE(cancelled,created)")
        connection.execute("CREATE TABLE IF NOT EXISTS booking_history (id INTEGER PRIMARY KEY, booking_id INTEGER NOT NULL REFERENCES bookings(id), action TEXT NOT NULL, changed INTEGER NOT NULL, snapshot TEXT NOT NULL)")
        connection.execute("CREATE INDEX IF NOT EXISTS booking_history_item ON booking_history(booking_id,id)")
        connection.execute("CREATE TABLE IF NOT EXISTS limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, resets INTEGER NOT NULL)")


def validate(connection):
    connection.execute("SELECT id,sequence,updated FROM bookings LIMIT 0")
    connection.execute("SELECT booking_id,snapshot FROM booking_history LIMIT 0")
    connection.execute("SELECT bucket,count,resets FROM limits LIMIT 0")
